---
language: ruby
rvm:
- '2.0'
- '2.1'
script: bundle exec rspec spec
gemfile:
- gemfiles/4.0.4.gemfile
- gemfiles/4.0.5.gemfile
- gemfiles/4.0.6.gemfile
- gemfiles/4.0.7.gemfile
- gemfiles/4.0.8.gemfile
- gemfiles/4.1.0.gemfile
- gemfiles/4.1.1.gemfile
- gemfiles/4.1.2.gemfile
- gemfiles/4.1.3.gemfile
- gemfiles/4.1.4.gemfile