---
language: ruby
rvm:
- '2.1'
- '2.2'
- '2.3'
script: bundle exec rspec spec
gemfile:
- gemfiles/4.0.10.gemfile
- gemfiles/4.0.10.rc1.gemfile
- gemfiles/4.0.10.rc2.gemfile
- gemfiles/4.0.11.1.gemfile
- gemfiles/4.0.11.gemfile
- gemfiles/4.0.12.gemfile
- gemfiles/4.0.13.gemfile
- gemfiles/4.0.13.rc1.gemfile
- gemfiles/4.0.4.gemfile
- gemfiles/4.0.5.gemfile
- gemfiles/4.0.6.gemfile
- gemfiles/4.0.6.rc1.gemfile
- gemfiles/4.0.6.rc2.gemfile
- gemfiles/4.0.6.rc3.gemfile
- gemfiles/4.0.7.gemfile
- gemfiles/4.0.8.gemfile
- gemfiles/4.0.9.gemfile
- gemfiles/4.1.0.beta1.gemfile
- gemfiles/4.1.0.beta2.gemfile
- gemfiles/4.1.0.gemfile
- gemfiles/4.1.0.rc1.gemfile
- gemfiles/4.1.0.rc2.gemfile
- gemfiles/4.1.1.gemfile
- gemfiles/4.1.10.gemfile
- gemfiles/4.1.10.rc1.gemfile
- gemfiles/4.1.10.rc2.gemfile
- gemfiles/4.1.10.rc3.gemfile
- gemfiles/4.1.10.rc4.gemfile
- gemfiles/4.1.11.gemfile
- gemfiles/4.1.12.gemfile
- gemfiles/4.1.12.rc1.gemfile
- gemfiles/4.1.13.gemfile
- gemfiles/4.1.13.rc1.gemfile
- gemfiles/4.1.14.1.gemfile
- gemfiles/4.1.14.2.gemfile
- gemfiles/4.1.14.gemfile
- gemfiles/4.1.14.rc1.gemfile
- gemfiles/4.1.14.rc2.gemfile
- gemfiles/4.1.15.gemfile
- gemfiles/4.1.15.rc1.gemfile
- gemfiles/4.1.16.gemfile
- gemfiles/4.1.16.rc1.gemfile
- gemfiles/4.1.2.gemfile
- gemfiles/4.1.2.rc1.gemfile
- gemfiles/4.1.2.rc2.gemfile
- gemfiles/4.1.2.rc3.gemfile
- gemfiles/4.1.3.gemfile
- gemfiles/4.1.4.gemfile
- gemfiles/4.1.5.gemfile
- gemfiles/4.1.6.gemfile
- gemfiles/4.1.6.rc1.gemfile
- gemfiles/4.1.6.rc2.gemfile
- gemfiles/4.1.7.1.gemfile
- gemfiles/4.1.7.gemfile
- gemfiles/4.1.8.gemfile
- gemfiles/4.1.9.gemfile
- gemfiles/4.1.9.rc1.gemfile
- gemfiles/4.2.0.beta1.gemfile
- gemfiles/4.2.0.beta2.gemfile
- gemfiles/4.2.0.beta3.gemfile
- gemfiles/4.2.0.beta4.gemfile
- gemfiles/4.2.0.gemfile
- gemfiles/4.2.0.rc1.gemfile
- gemfiles/4.2.0.rc2.gemfile
- gemfiles/4.2.0.rc3.gemfile
- gemfiles/4.2.1.gemfile
- gemfiles/4.2.1.rc1.gemfile
- gemfiles/4.2.1.rc2.gemfile
- gemfiles/4.2.1.rc3.gemfile
- gemfiles/4.2.1.rc4.gemfile
- gemfiles/4.2.2.gemfile
- gemfiles/4.2.3.gemfile
- gemfiles/4.2.3.rc1.gemfile
- gemfiles/4.2.4.gemfile
- gemfiles/4.2.4.rc1.gemfile
- gemfiles/4.2.5.1.gemfile
- gemfiles/4.2.5.2.gemfile
- gemfiles/4.2.5.gemfile
- gemfiles/4.2.5.rc1.gemfile
- gemfiles/4.2.5.rc2.gemfile
- gemfiles/4.2.6.gemfile
- gemfiles/4.2.6.rc1.gemfile
- gemfiles/4.2.7.1.gemfile
- gemfiles/4.2.7.gemfile
- gemfiles/4.2.7.rc1.gemfile
- gemfiles/5.0.0.1.gemfile
- gemfiles/5.0.0.beta1.1.gemfile
- gemfiles/5.0.0.beta1.gemfile
- gemfiles/5.0.0.beta2.gemfile
- gemfiles/5.0.0.beta3.gemfile
- gemfiles/5.0.0.beta4.gemfile
- gemfiles/5.0.0.gemfile
- gemfiles/5.0.0.racecar1.gemfile
- gemfiles/5.0.0.rc1.gemfile
- gemfiles/5.0.0.rc2.gemfile
